# Generated by Django 4.0 on 2025-01-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('state', models.CharField(max_length=36)),
                ('waiting_for_tokens', models.BooleanField(default=False)),
                ('token_request_code', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_expiry', models.DateTimeField()),
                ('refresh_token', models.CharField(max_length=100)),
                ('refresh_token_expiry', models.DateTimeField()),
            ],
        ),
    ]
