# Generated by Django 4.0 on 2025-01-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnvironment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretokens',
            name='access_token_expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='refresh_token_expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
