# Generated by Django 4.0 on 2025-01-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnvironment', '0002_alter_coretokens_access_token_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretokens',
            name='access_token_expiry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='refresh_token_expiry',
            field=models.DateTimeField(),
        ),
    ]
