# Generated by Django 4.0 on 2025-01-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnvironment', '0003_alter_coretokens_access_token_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretokens',
            name='access_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='state',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='token_request_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
