# Generated by Django 4.0 on 2025-01-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnvironment', '0005_remove_coretokens_waiting_for_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='coretokens',
            name='access_token_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='coretokens',
            name='endpoint',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
