# Generated by Django 4.0 on 2025-01-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testEnvironment', '0006_coretokens_access_token_type_coretokens_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coretokens',
            name='access_token',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='coretokens',
            name='token_request_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
