# Generated by Django 4.0 on 2021-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservice',
            options={'verbose_name_plural': 'Main Services'},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name_plural': 'Sub Services'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
