# Generated by Django 4.0 on 2021-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0002_alter_mainservice_options_alter_subservice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
