# Generated by Django 4.0 on 2021-12-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0003_alter_technology_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='image',
        ),
    ]
