# Generated by Django 4.0 on 2021-12-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0004_remove_subservice_technologies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
